"""add_tkbi_flow_fields

Revision ID: 8c9f21ee31fd
Revises: f6d22d0fd947
Create Date: 2026-10-08 07:34:13.826129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9f21ee31fd'
down_revision: Union[str, Sequence[str], None] = 'f6d22d0fd947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_runs', sa.Column('entity_aggregation', sa.JSON(), nullable=True))
    op.add_column('audit_runs', sa.Column('activities_breakdown', sa.JSON(), nullable=True))
    op.add_column('audit_runs', sa.Column('scale_type', sa.String(length=32), server_default='KORPORASI', nullable=False))
    op.add_column('tkbi_audit_entries', sa.Column('eo_category', sa.String(length=16), nullable=True))
    op.add_column('tkbi_audit_entries', sa.Column('dnsh_status', sa.String(length=32), nullable=True))
    op.add_column('tkbi_audit_entries', sa.Column('rmt_status', sa.String(length=64), nullable=True))
    op.add_column('tkbi_audit_entries', sa.Column('social_status', sa.String(length=32), nullable=True))
    op.add_column('tkbi_audit_entries', sa.Column('is_interim', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tkbi_audit_entries', 'is_interim')
    op.drop_column('tkbi_audit_entries', 'social_status')
    op.drop_column('tkbi_audit_entries', 'rmt_status')
    op.drop_column('tkbi_audit_entries', 'dnsh_status')
    op.drop_column('tkbi_audit_entries', 'eo_category')
    op.drop_column('audit_runs', 'scale_type')
    op.drop_column('audit_runs', 'activities_breakdown')
    op.drop_column('audit_runs', 'entity_aggregation')
    # ### end Alembic commands ###
