"""initial_schema

Revision ID: f6d22d0fd947
Revises: 
Create Date: 2026-10-03 05:39:49.081633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d22d0fd947'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('subsector', sa.String(length=128), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('viability_score', sa.Float(), nullable=False),
    sa.Column('quadrant', sa.String(length=64), nullable=True),
    sa.Column('quadrant_label', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('financial_snapshot', sa.JSON(), nullable=True),
    sa.Column('audit_findings', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_id'), 'audit_runs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_runs_status'), 'audit_runs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_runs_ticker'), 'audit_runs', ['ticker'], unique=False)
    op.create_index(op.f('ix_audit_runs_trace_id'), 'audit_runs', ['trace_id'], unique=False)
    op.create_table('audit_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_traces_span_id'), 'audit_traces', ['span_id'], unique=False)
    op.create_index(op.f('ix_audit_traces_trace_id'), 'audit_traces', ['trace_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold_score', sa.Float(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_id'), 'scheduled_jobs', ['id'], unique=False)
    op.create_table('tkbi_audit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_run_id', sa.String(length=64), nullable=False),
    sa.Column('kode_emiten', sa.String(length=16), nullable=False),
    sa.Column('sektor', sa.String(length=128), nullable=False),
    sa.Column('bab', sa.String(length=255), nullable=False),
    sa.Column('kbli', sa.String(length=64), nullable=False),
    sa.Column('tsc_id', sa.String(length=64), nullable=False),
    sa.Column('tsc', sa.String(length=255), nullable=False),
    sa.Column('bentuk_jawaban', sa.String(length=64), nullable=False),
    sa.Column('jawaban_ai', sa.String(length=32), nullable=False),
    sa.Column('keyakinan_ai', sa.String(length=32), nullable=False),
    sa.Column('reasoning_ai', sa.Text(), nullable=True),
    sa.Column('bukti', sa.Text(), nullable=True),
    sa.Column('auditor_feedback', sa.Text(), nullable=True),
    sa.Column('auditor_override', sa.String(length=32), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tkbi_audit_entries_audit_run_id'), 'tkbi_audit_entries', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_tkbi_audit_entries_kode_emiten'), 'tkbi_audit_entries', ['kode_emiten'], unique=False)
    op.create_index(op.f('ix_tkbi_audit_entries_tsc_id'), 'tkbi_audit_entries', ['tsc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tkbi_audit_entries_tsc_id'), table_name='tkbi_audit_entries')
    op.drop_index(op.f('ix_tkbi_audit_entries_kode_emiten'), table_name='tkbi_audit_entries')
    op.drop_index(op.f('ix_tkbi_audit_entries_audit_run_id'), table_name='tkbi_audit_entries')
    op.drop_table('tkbi_audit_entries')
    op.drop_index(op.f('ix_scheduled_jobs_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_audit_traces_trace_id'), table_name='audit_traces')
    op.drop_index(op.f('ix_audit_traces_span_id'), table_name='audit_traces')
    op.drop_table('audit_traces')
    op.drop_index(op.f('ix_audit_runs_trace_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_ticker'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_status'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    # ### end Alembic commands ###
